### ISSUE TITLE
Potential Memory Leak at Title Screen - Requires Investigation

### ISSUE THREAD

**Issue by razavidn** [mcanterb/JRGSS#12]
Memory usage seems to steadily climb while title screen is displayed; levels off once the game starts.

**Comment by mcanterb** [comment]
I'll look into it. The Vidar Title screen loads a series of images to play the background animation, so this may be what you're seeing. However, I wouldn't be surprised to find a memory leak.

**Comment by mcanterb** [comment]
There is definitely a memory leak here. After letting the Title screen loop a few times, Memory usage was around 4GB and increasing. My first guess would be improper handling of a dispose method somewhere. Next would be a cache using an incorrectly configured key (a key without a proper hashCode method)
